### ISSUE TITLE
roms u18 and u19 missing

### ISSUE THREAD

**Issue by joriszwart** [folkertvanheusden/DotXT#5]
The zip archive [BIOS_5160_16AUG82.zip](https://github.com/folkertvanheusden/DotXT/blob/c8e4733cce012a5886477fc17a875e92ddf9aa56/roms/BIOS_5160_16AUG82.zip) does not contain *u18.rom* and *u19.rom*.

https://github.com/folkertvanheusden/DotXT/blob/650a49cbd15ef3feb09aa81bfe20b0c5dea2db56/memory.cs#L49-L50

**Comment by folkertvanheusden** [comment]
Fixed by #6
